name: BMIDE Package Deploy

on: [push]

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps: 
      - name: Generate BMIDE Package
        run: |
            cd C:\Exxon\TC14\tc_root\bin
            bmide_generate_package.bat -projectLocation=e4exombase -packageLocation=e4exombase/output/wntx64/packaging/full_update -dependencyTemplateFolder=%TC_ROOT%\bmide\templates -softwareVersion="1.0" -buildVersion=$(date -u +"%Y%m%d") -log=%TEMP%\bmidegenpack.log
